### ISSUE TITLE
Añadir "Monstercat FM" como "Electro"

### ISSUE THREAD

**Issue by justalemon** [perronosaurio/baba-radio#1]
Aunque no siga el formato actual, [Monstercat FM](http://live.monstercat.com) es una transmisión 24/7 de musica electronica que podría servir usando el stream de Twitch o YouTube (que se pueden redirigir a Discord).

https://github.com/OverwatchLatino/monstercat puede ser usado como ejemplo.

**Comment by perronosaurio** [comment]
Gracias por el consejo, también tengo pensado añadir más cosas.

**Comment by Alonso245** [comment]
omg soy famoso :D

**Comment by Alonso245** [comment]
Aparezco en el git-hub LOG 😄

**Comment by justalemon** [comment]
Apareces por ser imbecil

**Comment by Alonso245** [comment]
Adivinaste :3

**Comment by justalemon** [comment]
@perronosaurio Me haces el favor de presionar ese botón?
![image](https://user-images.githubusercontent.com/11861253/31362687-2ca30e42-ad30-11e7-8dae-eaa948e335c3.png)
